brain_two/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include("todos.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("todos_list")), name="home"),
]

todos/urls.py
from django.urls import path

from todos.views import TodoDeleteView, TodoDetailView, TodoItemCreateView, TodoItemUpdateView, TodoListView, TodoCreateView, TodoUpdateView

urlpatterns = [
    path("", TodoListView.as_view(), name="todos_list"),
    path("<int:pk>/", TodoDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoCreateView.as_view(), name="todo_list_create"),
    path("<int:pk>/edit/", TodoUpdateView.as_view(), name="todo_list_edit"),
    path("<int:pk>/delete/", TodoDeleteView.as_view(), name="todo_list_delete"),
    path("items/create/", TodoItemCreateView.as_view(), name="todo_item_create"),
    path("items/<int:pk>/edit/", TodoItemUpdateView.as_view(), name="todo_item_edit"),
]

todos/models.py
from django.db import models

# Create your models here.

class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length=100, null=True)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    #might have to change this to a null = false default
    list = models.ForeignKey(TodoList, related_name="items", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from todos.models import TodoItem, TodoList

# Create your views here.

class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"

class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todos/new.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"

class TodoUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/edit.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

class TodoDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("todos_list")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todos/items/create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todos/items/edit.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Delete Todo</title>
  </head>

  <body>
    <header>
    </header>

    <main>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <div>
            <button class="button">Delete</button>
          </div>
        </form>
      </main>

  </body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todo Detail</title>
  </head>
  <body>
    <div>
        <a href="{% url 'todos_list' %}">Back to list</a>
        <a href="{% url 'todo_list_edit' todolist.id %}">Edit</a>
        <a href="{% url 'todo_list_delete' todolist.id %}">Delete</a>
    </div>
    <h1> {{ todolist.name }} </h1>

    <header>
     <h2>Tasks</h2>
    </header>
    <h3>Task Due date</h3>


    <p> {% for task in todolist.items.all %}
        <div>
        <a href="{% url 'todo_item_edit' task.id %}"> {{ task }} </a> {{ task.due_date|date:"M d, Y" }}
        </div>
        {% endfor %} </p>

  </body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Update Todo</title>
  </head>

  <body>
    <header>
    </header>

    <main>
        <form method="post">
            {% csrf_token %} {{ form.as_p }}
            <div class="control">
                <button class="button">Submit</button>
            </div>
        </form>
    </main>

  </body>
</html>

todos/templates/todos/items/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create Todo ITEM</title>
  </head>

  <body>
    <header>
    </header>
    <main>
        <form method="post">
            {% csrf_token %} {{ form.as_p }}
            <div class="control">
                <button class="button">Submit</button>
            </div>
        </form>
    </main>


  </body>
</html>

todos/templates/todos/items/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Update Todo Item</title>
  </head>

  <body>
    <header>
    </header>

    <main>
      <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <div class="control">
              <button class="button">Submit</button>
          </div>
      </form>

  </main>
  </body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todos List</title>
  </head>

  <body>
    <header>
     <h1>My lists</h1>
    </header>

    <div>
            <a href="{% url 'todo_list_create' %}">Create a new list</a>

            <a href="{% url 'todo_item_create' %}">Create a new item</a>

            <h3>Name Number of Items</h3>
    </div>
    {% for todo in todolist_list%}
    <div>
      <td>
    <a href="{% url 'todo_list_detail' todo.pk %}"> {{ todo.name }} </a>
      </td>
      <td>
                 {{ todo.items.all|length }}
      </td>


    </div>
    {% endfor %}
        {% comment %} Insert some kind of python logic -- if name exists, put a link to the detail page , etc. {% endcomment %}
  </body>
</html>

todos/templates/todos/new.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create Todo</title>
  </head>
  <body>
    <header>
    </header>
    <main>
        <form method="post">
            {% csrf_token %} {{ form.as_p }}
            <div class="control">
                <button class="button">Submit</button>
            </div>
        </form>
    </main>

  </body>
</html>